-- Script de création de la table DETAIL pour OCC
-- À exécuter dans votre base Oracle avant d'utiliser le pipeline TMP->DETAIL

-- 1. Créer la table RA_T_OCC_CDR_DETAIL
CREATE TABLE RA_T_OCC_CDR_DETAIL (
    DATASOURCE VARCHAR2(20) NOT NULL,
    A_MSISDN VARCHAR2(200) NOT NULL,
    B_MSISDN VARCHAR2(200),
    START_DATE DATE NOT NULL,
    START_HOUR NUMBER(2),
    APN VARCHAR2(50) NOT NULL,
    CALL_TYPE VARCHAR2(20) NOT NULL,
    EVENT_TYPE VARCHAR2(20) NOT NULL,
    CHARGING_ID VARCHAR2(40) NOT NULL,
    SERVICE_ID VARCHAR2(40) NOT NULL,
    SUBSCRIBER_TYPE VARCHAR2(30) NOT NULL,
    ROAMING_TYPE VARCHAR2(10) NOT NULL,
    PARTNER VARCHAR2(20) NOT NULL,
    EVENT_COUNT NUMBER(30,0),
    DATA_VOLUME NUMBER(30,5),
    EVENT_DURATION NUMBER(30,0),
    CHARGE_AMOUNT NUMBER(20,5),
    FILTER_CODE VARCHAR2(20) NOT NULL,
    KEYWORD VARCHAR2(100) DEFAULT '_N',
    ORIG_START_TIME VARCHAR2(70),
    DA_AMOUNT_CALC NUMBER(20,5),
    MA_AMNT_CALC NUMBER(20,5),
    FLEX_FLD1 VARCHAR2(100) NOT NULL,
    FLEX_FLD2 VARCHAR2(100) NOT NULL,
    FLEX_FLD3 VARCHAR2(100) NOT NULL
);

-- 2. Créer un index unique sur CHARGING_ID pour la déduplication
-- IMPORTANT: cet index garantit qu'on ne peut pas avoir de doublons
CREATE UNIQUE INDEX UK_OCC_CHARGING_ID ON RA_T_OCC_CDR_DETAIL(CHARGING_ID);

-- 3. Créer des index supplémentaires pour les requêtes fréquentes (optionnel)
CREATE INDEX IDX_OCC_START_DATE ON RA_T_OCC_CDR_DETAIL(START_DATE);
CREATE INDEX IDX_OCC_A_MSISDN ON RA_T_OCC_CDR_DETAIL(A_MSISDN);
CREATE INDEX IDX_OCC_CALL_TYPE ON RA_T_OCC_CDR_DETAIL(CALL_TYPE);

-- 4. Optionnel: Ajouter des commentaires sur la table
COMMENT ON TABLE RA_T_OCC_CDR_DETAIL IS 'Table DETAIL pour les CDR OCC - données nettoyées et typées';
COMMENT ON COLUMN RA_T_OCC_CDR_DETAIL.CHARGING_ID IS 'Clé unique de déduplication';
COMMENT ON COLUMN RA_T_OCC_CDR_DETAIL.START_DATE IS 'Date convertie depuis ORIG_START_TIME (timestamp epoch)';
COMMENT ON COLUMN RA_T_OCC_CDR_DETAIL.ORIG_START_TIME IS 'Timestamp original du CSV (traçabilité)';

-- 5. Vérifier la création
SELECT COUNT(*) FROM RA_T_OCC_CDR_DETAIL;

-- 6. (Optionnel) Créer une vue pour faciliter les requêtes
CREATE OR REPLACE VIEW V_OCC_CDR_RECENT AS
SELECT *
FROM RA_T_OCC_CDR_DETAIL
WHERE START_DATE >= TRUNC(SYSDATE) - 30
ORDER BY START_DATE DESC;

COMMENT ON VIEW V_OCC_CDR_RECENT IS 'CDR OCC des 30 derniers jours';
